global:
  imagePullPolicy: Always
  secrets: "/run/secrets"
  vault:
    image: "hashicorp/vault:1.21.0"
    addr: http://vault:8200
    spring:
      import: "vault://kv/sausage-store"
    token: ""
    resources:
      container:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"

frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: YOUR_STUDENT_HOSTNAME.students-projects.ru # Корректный домен будет указан в задании
    path: /
    pathType: Prefix
  containerPort: 80
  image: YOUR_DOCKERHUB/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "800m"
  nginxConf: nginx.conf

backend:
  image: itmo508541/sausage-backend:latest
  containerPort: 8080
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    reportPath: /logs
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
  resources:
    container:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "800m"
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: backend
    initialDelaySeconds: 45
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: backend
    initialDelaySeconds: 90
    periodSeconds: 20
  vpa:
    updatePolicy:
      updateMode: "InPlaceOrRecreate"
    resourcePolicy:
      containerPolicies:
        - containerName: "backend"
          minAllowed:
            memory: "256Mi"
            cpu: "100m"
          maxAllowed:
            memory: "1Gi"
            cpu: "1600m"
          controlledResources:
            - memory
            - cpu
          controlledValues: RequestsAndLimits

### Опишите HPA для backend-report
backend-report:
  image: itmo508541/sausage-backend-report:latest
  containerPort: 8080
  health: "/api/v1/health"
  replicas: 1
  strategy:
    type: Recreate
  resources:
    container:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"

infra:
  postgresql:
    image: postgres:16
    containerPort: 5432
    resources:
      container:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "256Mi"
          cpu: "300m"
      data:
        requests:
          storage: 1Gi
  mongodb:
    image: mongo:7.0
    containerPort: 27017
    resources:
      container:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "100m"
      data:
        requests:
          storage: 1Gi
