---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      {{- include "selector.labels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "selector.labels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      initContainers:
        - name: mongodb-vault-secrets
          image: {{ .Values.global.vault.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.global.vault.addr | quote }}
            - name: VAULT_TOKEN
              value: {{ .Values.global.vault.token | quote }}
          {{- with .Values.global.vault.resources.container }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: mongodb-secrets
              mountPath: {{ .Values.global.secrets }}
          command:
            - sh
            - -c
            - |
              set -e
              vault status
              vault kv get -mount=kv -field=mongodb.init.username sausage-store > {{ .Values.global.secrets }}/mongo-root-username
              vault kv get -mount=kv -field=mongodb.init.password sausage-store > {{ .Values.global.secrets }}/mongo-root-password
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: "{{ .Values.global.secrets }}/mongo-root-username"
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: "{{ .Values.global.secrets }}/mongo-root-password"
          ports:
          - containerPort: {{ .Values.mongodb.containerPort }}
          {{- with .Values.mongodb.resources.container }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: mongodb-data
            mountPath: /data/db
          - name: mongodb-secrets
            mountPath: {{ .Values.global.secrets }}
            readOnly: true
      volumes:
        - name: mongodb-secrets
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "metadata.labels" . | nindent 10 }}
          app.kubernetes.io/component: mongodb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- with .Values.mongodb.resources.data }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  ports:
    - port: {{ .Values.mongodb.containerPort }}
      targetPort: {{ .Values.mongodb.containerPort }}
  selector:
    {{- include "selector.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
  clusterIP: None
