---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "selector.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "template.metadata.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- with .Values.resources.container }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.containerPort }}
          volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            mountPath: /etc/nginx/{{ .Values.nginxConf }}
            subPath: {{ .Values.nginxConf }}
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            items:
              - key: {{ .Values.nginxConf }}
                path: {{ .Values.nginxConf }}
