---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "selector.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selector.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-vault-secrets
          image: {{ .Values.global.vault.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.global.vault.addr | quote }}
            - name: VAULT_TOKEN
              value: {{ .Values.global.vault.token | quote }}
          {{- with .Values.global.vault.resources.container }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
              mountPath: {{ .Values.global.secrets }}
          command:
            - sh
            - -c
            - |
              set -e
              vault status
              printf 'DB="%s"\n' "$(vault kv get -mount=kv -field=spring.data.mongodb.uri sausage-store)" > {{ .Values.global.secrets }}/env
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          readinessProbe:
            httpGet:
              path: {{ .Values.health }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.health }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
                  key: port
          {{- with .Values.resources.container }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
              mountPath: {{ .Values.global.secrets }}
              readOnly: true
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
          emptyDir: {}
