apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-vault-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.global.vault.token | b64enc }}
