---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    {{- include "selector.labels" . | nindent 4 }}
