name: Sausage Store Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub_backend:
    name: Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Backend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: itmo508541/sausage-backend:latest
          build-args: |
            VERSION=${{ github.sha }}
          cache-from: type=registry,ref=itmo508541/sausage-backend:latest
          cache-to: type=registry,ref=itmo508541/sausage-backend:cache,mode=max

  build_and_push_to_docker_hub_frontend:
    name: Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: itmo508541/sausage-frontend:latest
          cache-from: type=registry,ref=itmo508541/sausage-frontend:latest
          cache-to: type=registry,ref=itmo508541/sausage-frontend:cache,mode=max

  build_and_push_to_docker_hub_backend_report:
    name: Backend-Report Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Backend-report to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend-report/
          push: true
          tags: itmo508541/sausage-backend-report:latest
          cache-from: type=registry,ref=itmo508541/sausage-backend-report:latest
          cache-to: type=registry,ref=itmo508541/sausage-backend-report:cache,mode=max

  # Упаковываем helm-чарт и пушим его в Nexus
  add_helm_chart_to_nexus:
    name: Add Helm Chart To Nexus
    runs-on: ubuntu-latest
    needs:
      - build_and_push_to_docker_hub_backend
      - build_and_push_to_docker_hub_frontend
      - build_and_push_to_docker_hub_backend_report
    env:
      HELM_REPO_USERNAME: ${{ secrets.NEXUS_HELM_REPO_USER }}
      HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
      HELM_REPO_CONTEXT_PATH: ${{ secrets.NEXUS_HELM_REPO_CONTEXT_PATH }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Install helm cm-push plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push.git
      - name: Package Helm Chart
        run: |
          helm package ./sausage-store-chart
      - name: Push Helm Chart
        run: |
          helm cm-push sausage-store-*.tgz "${{ secrets.NEXUS_HELM_REPO }}"

  deploy_helm_chart_to_kubernetes:
    name: Deploy Helm Chart To Kubernetes
    runs-on: ubuntu-latest
    needs: add_helm_chart_to_nexus

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      - name: Upgrade Helm release
        run: |
          helm repo add nexus "${{ secrets.NEXUS_HELM_REPO }}" --username "${{ secrets.NEXUS_HELM_REPO_USER }}" --password "${{ secrets.NEXUS_HELM_REPO_PASSWORD }}"
          helm repo update
          helm upgrade --install sausage-store nexus/sausage-store --set global.vault.token='${{ secrets.VAULT_TOKEN }}' --wait --timeout 10m
